### ISSUE TITLE
Simplified version ?

### ISSUE THREAD

**Issue by josojo** [appliedzkp/maci#414]
Have you guys seen: https://ethresear.ch/t/saci-simplified-anti-coliusion-infrastructure/12494

Do you guys think it's a valuable simplification, or does it have too many trade-offs? Would love to hear your opinion.

**Comment by daodesigner** [comment]
> Have you guys seen: https://ethresear.ch/t/saci-simplified-anti-coliusion-infrastructure/12494
> 
> 
> 
> Do you guys think it's a valuable simplification, or does it have too many trade-offs? Would love to hear your opinion.

MACI, the _mechanism_ is different from the zkSNARK MACI (implementation) in this repo. At first glance, the post linked looks like a different mechanism altogether with some explicit implementation details. It's not immediately clear if the steps in the modified mechanism are correct (by construction or otherwise) and any mechanism that falls back on sacrificing user privacy is a fail to start.
